export const STRINGS = {
  en: {
    tagline: 'Reading, on your terms',
    connected: 'connected',
    offline: 'offline',
    checking: 'checking…',
    size: 'Size',
    spacing: 'Line spacing',
    dark: 'Dark',
    light: 'Light',
    readAloud: 'Read aloud',
    stop: 'Stop',
    dictate: 'Dictate',
    listening: 'Listening…',
    history: 'History',
    ledeA: 'Every reader needs',
    ledeB: 'something',
    ledeEm: 'different.',
    sub: "Paste a document. Lexi rewrites it for the way you read, shows you exactly what changed, and tells you where it wasn't certain.",
    placeholder: 'Paste a form, an article, a contract, a chapter…',
    words: 'words',
    openFile: 'Open a file…',
    rewriteFor: 'Rewrite for',
    rewriteForNote: 'Each option restructures the text differently — not just the wording.',
    howFar: 'How far to simplify',
    levels: ['barely', 'light', 'balanced', 'strong', 'simplest'],
    rewriteBtn: 'Rewrite this',
    rewriting: 'Rewriting…',
    rewriteNote: 'A few seconds for short text. Longer documents take longer.',
    whatChanged: 'What changed',
    copy: 'Copy',
    copied: 'Copied',
    asWritten: 'As written',
    rewritten: 'Rewritten',
    level: 'level',
    grade: 'Reading grade',
    wps: 'Words / sentence',
    sentences: 'Sentences',
    confidence: 'Confidence',
    was: 'was',
    flags: 'Check these yourself',
    noFlags: 'No meaning drift detected.',
    goDeeper: 'Go deeper',
    goDeeperNote: 'Generated on request, from this document only.',
    keyPoints: 'Key points',
    glossary: 'Glossary',
    flashcards: 'Flashcards',
    diagram: 'Diagram',
    loadTab: 'Pick one to load',
    askTitle: 'Ask about this document',
    askHint: 'Answers come from your document only — in English or Bangla.',
    askPlaceholder: 'Type your question…',
    ask: 'Ask',
    you: 'You',
    thinking: 'thinking…',
    notFound: "That doesn't appear to be in this document.",
    emptyFirst: 'Add some text above to begin.',
    pdfBanglaWarn: 'PDF export does not support Bangla yet — use .txt',
    flip: 'Tap to flip',
    of: 'of',
    question: 'Question',
    answer: 'Answer',
    nothingViz: 'Nothing to visualise here.',
    sessionTitle: 'This session',
    close: 'Close',
    clearHistory: 'Clear history',
    historyEmpty: "Nothing yet. Rewrite something and it'll appear here.",
    blankK: 'Nothing yet',
    blankH1: 'Paste something on the left,',
    blankH2: 'pick how you read,',
    blankEm: 'and go.',
    blankP: 'Your rewrite appears here — alongside what changed, where meaning may have drifted, and everything you can do with it afterwards.',
    trySample: 'Try it with a sample paragraph',
    step1h: 'It rewrites',
    step1p: 'Restructured for your specific reading barrier, at the level you choose.',
    step2h: 'It checks itself',
    step2p: 'A second pass flags anything where meaning may have shifted.',
    step3h: 'You go deeper',
    step3p: 'Key points, glossary, flashcards, diagrams — and questions answered from your document.',
    suggest1: 'What do I have to do?',
    suggest2: 'Is there a deadline?',
    suggest3: 'What does this cost?',
    modeNames: {
      dyslexia: 'Dyslexia-Friendly',
      focus: 'Focus Mode',
      screen_reader: 'Screen Reader',
      non_native: 'Non-Native English',
      civic: 'Civic / Forms',
      dyscalculia: 'Dyscalculia',
      adhd: 'ADHD-Friendly',
    },
    modeDescs: {
      dyslexia: 'Short sentences, simple words, clear spacing.',
      focus: 'Key points up front, bullets, bolded essentials.',
      screen_reader: 'Speech-friendly punctuation and structure.',
      non_native: 'Simpler vocabulary with inline clarifications.',
      civic: 'Requirements, deadlines, fees, and steps.',
      dyscalculia: 'Numbers and tables in plain language.',
      adhd: 'Short chunks, key action first, bolded essentials.',
    },
  },

  bn: {
    tagline: 'পড়া, আপনার নিজের নিয়মে',
    connected: 'সংযুক্ত',
    offline: 'বিচ্ছিন্ন',
    checking: 'পরীক্ষা করা হচ্ছে…',
    size: 'আকার',
    spacing: 'লাইন ফাঁক',
    dark: 'ডার্ক',
    light: 'লাইট',
    readAloud: 'পড়ে শোনাও',
    stop: 'থামাও',
    dictate: 'বলুন',
    listening: 'শুনছি…',
    history: 'ইতিহাস',
    ledeA: 'প্রত্যেক পাঠকের প্রয়োজন',
    ledeB: 'আলাদা',
    ledeEm: 'কিছু।',
    sub: 'একটি ডকুমেন্ট পেস্ট করুন। Lexi সেটিকে আপনার পড়ার ধরন অনুযায়ী নতুন করে লিখবে, কী বদলেছে তা দেখাবে, আর কোথায় নিশ্চিত ছিল না তা জানাবে।',
    placeholder: 'একটি ফর্ম, নিবন্ধ, চুক্তি বা অধ্যায় পেস্ট করুন…',
    words: 'শব্দ',
    openFile: 'ফাইল খুলুন…',
    rewriteFor: 'কার জন্য লিখব',
    rewriteForNote: 'প্রতিটি অপশন টেক্সট আলাদাভাবে সাজায় — শুধু শব্দ বদলায় না।',
    howFar: 'কতটা সহজ করব',
    levels: ['সামান্য', 'হালকা', 'ভারসাম্য', 'বেশি', 'সবচেয়ে সহজ'],
    rewriteBtn: 'নতুন করে লিখুন',
    rewriting: 'লেখা হচ্ছে…',
    rewriteNote: 'ছোট টেক্সটে কয়েক সেকেন্ড। বড় ডকুমেন্টে বেশি সময় লাগে।',
    whatChanged: 'কী বদলেছে',
    copy: 'কপি',
    copied: 'কপি হয়েছে',
    asWritten: 'যেমন লেখা ছিল',
    rewritten: 'নতুন করে লেখা',
    level: 'মাত্রা',
    grade: 'পড়ার স্তর',
    wps: 'শব্দ / বাক্য',
    sentences: 'বাক্য',
    confidence: 'নির্ভরযোগ্যতা',
    was: 'ছিল',
    flags: 'এগুলো নিজে দেখে নিন',
    noFlags: 'অর্থ বদলের কোনো লক্ষণ পাওয়া যায়নি।',
    goDeeper: 'আরও গভীরে',
    goDeeperNote: 'শুধু এই ডকুমেন্ট থেকে, চাইলে তৈরি হয়।',
    keyPoints: 'মূল বিষয়',
    glossary: 'শব্দকোষ',
    flashcards: 'ফ্ল্যাশকার্ড',
    diagram: 'চিত্র',
    loadTab: 'একটি বেছে নিন',
    askTitle: 'এই ডকুমেন্ট নিয়ে প্রশ্ন করুন',
    askHint: 'উত্তর শুধু আপনার ডকুমেন্ট থেকে আসে — ইংরেজি বা বাংলায়।',
    askPlaceholder: 'আপনার প্রশ্ন লিখুন…',
    ask: 'জিজ্ঞাসা',
    you: 'আপনি',
    thinking: 'ভাবছি…',
    notFound: 'এটি এই ডকুমেন্টে পাওয়া যায়নি।',
    emptyFirst: 'শুরু করতে উপরে কিছু লেখা যোগ করুন।',
    pdfBanglaWarn: 'PDF এখনো বাংলা সমর্থন করে না — .txt ব্যবহার করুন',
    flip: 'উল্টাতে চাপ দিন',
    of: 'এর',
    question: 'প্রশ্ন',
    answer: 'উত্তর',
    nothingViz: 'এখানে দেখানোর মতো কিছু নেই।',
    sessionTitle: 'এই সেশন',
    close: 'বন্ধ',
    clearHistory: 'ইতিহাস মুছুন',
    historyEmpty: 'এখনো কিছু নেই। কিছু নতুন করে লিখলে এখানে দেখা যাবে।',
    blankK: 'এখনো কিছু নেই',
    blankH1: 'বাঁ পাশে কিছু পেস্ট করুন,',
    blankH2: 'আপনি কীভাবে পড়েন বেছে নিন,',
    blankEm: 'তারপর শুরু।',
    blankP: 'আপনার নতুন লেখা এখানে আসবে — সঙ্গে কী বদলেছে, কোথায় অর্থ সরে যেতে পারে, আর তারপর কী কী করা যায় তার সবকিছু।',
    trySample: 'একটি নমুনা অনুচ্ছেদ দিয়ে দেখুন',
    step1h: 'নতুন করে লেখে',
    step1p: 'আপনার নির্দিষ্ট পড়ার অসুবিধা অনুযায়ী, আপনার বেছে নেওয়া মাত্রায় সাজানো হয়।',
    step2h: 'নিজের কাজ যাচাই করে',
    step2p: 'দ্বিতীয় একটি ধাপ দেখে কোথায় অর্থ বদলে যেতে পারে, সেটি চিহ্নিত করে।',
    step3h: 'আরও গভীরে যান',
    step3p: 'মূল বিষয়, শব্দকোষ, ফ্ল্যাশকার্ড, চিত্র — আর আপনার ডকুমেন্ট থেকেই প্রশ্নের উত্তর।',
    suggest1: 'আমাকে কী করতে হবে?',
    suggest2: 'কোনো শেষ তারিখ আছে?',
    suggest3: 'এতে খরচ কত?',
    modeNames: {
      dyslexia: 'ডিসলেক্সিয়া-বান্ধব',
      focus: 'ফোকাস মোড',
      screen_reader: 'স্ক্রিন রিডার',
      non_native: 'সহজ ইংরেজি',
      civic: 'সরকারি ফর্ম',
      dyscalculia: 'ডিসক্যালকুলিয়া',
      adhd: 'ADHD-বান্ধব',
    },
    modeDescs: {
      dyslexia: 'ছোট বাক্য, সহজ শব্দ, পরিষ্কার ফাঁক।',
      focus: 'মূল বিষয় আগে, বুলেট পয়েন্ট, গুরুত্বপূর্ণ অংশ বোল্ড।',
      screen_reader: 'উচ্চারণ-বান্ধব যতিচিহ্ন ও গঠন।',
      non_native: 'সহজ শব্দভাণ্ডার, প্রয়োজনে ব্যাখ্যা সহ।',
      civic: 'প্রয়োজনীয় কাগজ, সময়সীমা, ফি ও ধাপ।',
      dyscalculia: 'সংখ্যা ও টেবিল সহজ ভাষায়।',
      adhd: 'ছোট অংশে ভাগ, জরুরি কাজ আগে, বোল্ড করা মূল বিষয়।',
    },
  },
}

export const hasBangla = (s) => /[\u0980-\u09FF]/.test(s || '')